version: "3.8"

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - default

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: Fariz
      MYSQL_PASSWORD: 3151936f
      MYSQL_ROOT_PASSWORD: 3151936f
      MYSQL_DATABASE: test_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 3151936f
    links:
      - db
